import type {
  HomeSection,
  SectionTemplate,
  NavItem,
  LoadingSettings,
  BrandingSettings,
  FooterSettings,
  PageBlock,
} from "./types"

export const defaultHomeSections: HomeSection[] = [
  {
    section_key: "hero",
    title: "GZV Ltd",
    subtitle: "The Next-Gen Company",
    description: "Đồng hành cùng doanh nghiệp và thế hệ trẻ qua Marketing, Sales và Digital Transformation với tư duy triển khai thực chiến.",
    button_label: "Khám phá dịch vụ",
    button_url: "/dich-vu",
    sort_order: 10,
    item_limit: 1,
    is_visible: true,
    settings: {
      video_url: "/Intro.mp4",
    },
  },
  {
    section_key: "about_gzv",
    title: "CÂU CHUYỆN GZV",
    subtitle: "Từ một cộng đồng học hỏi đến hệ sinh thái triển khai thực chiến.",
    description: "GZV được xây dựng để kết nối thế hệ trẻ, chuyên gia và doanh nghiệp trong cùng một môi trường học tập - làm thật - tạo tác động thật. Chúng tôi tin rằng năng lực chỉ bền vững khi được rèn trong dự án thực tế, dưới sự đồng hành của những người có kinh nghiệm.",
    button_label: "Xem chi tiết",
    button_url: "/gioi-thieu",
    sort_order: 20,
    item_limit: 1,
    is_visible: true,
    settings: {
      eyebrow: "GIỚI THIỆU",
      image_url: "/gioi-thieu/19.webp",
      image_alt: "GZV",
      position_x: 50,
      position_y: 50,
      image_size: 100,
      button_label: "Xem chi tiết",
      button_url: "/gioi-thieu",
    },
  },
  {
    section_key: "projects",
    title: "DỰ ÁN ĐÃ TRIỂN KHAI",
    subtitle: "Những chiến dịch và dự án tiêu biểu do GZV cùng đối tác triển khai",
    description: "Danh sách các dự án thực chiến đã mang lại giá trị đo lường được cho doanh nghiệp.",
    button_label: "Xem tất cả dự án",
    button_url: "/du-an",
    sort_order: 30,
    item_limit: 6,
    is_visible: true,
    settings: {
      background: "#ffffff",
    },
  },
  {
    section_key: "services_three",
    title: "SERVICES",
    subtitle: "Marketing | Sales | Digital Transformation | Education | Events",
    description: "Giải pháp đào tạo, tư vấn và triển khai thực chiến cho cá nhân & doanh nghiệp.",
    button_label: "Xem tất cả dịch vụ",
    button_url: "/dich-vu",
    sort_order: 40,
    item_limit: 3,
    is_visible: true,
    settings: {
      services: [
        { title: "MARKETING & BRANDING", description: "Đào tạo thực chiến & tư vấn chiến lược marketing tổng thể, phát triển thương hiệu đa kênh.", link: "/dich-vu/marketing", icon: "megaphone" },
        { title: "SALES & PHÁT TRIỂN DOANH SỐ", description: "Xây dựng quy trình bán hàng, tối ưu hóa tỷ lệ chuyển đổi và mở rộng thị trường.", link: "/dich-vu", icon: "trend" },
        { title: "DIGITAL TRANSFORMATION", description: "Ứng dụng công nghệ, AI và tự động hóa quy trình vận hành doanh nghiệp hiệu quả.", link: "/dich-vu", icon: "cpu" },
      ],
    },
  },
  {
    section_key: "about_boxes",
    title: "VỀ CHÚNG TÔI",
    subtitle: "Đội ngũ nhân sự, chuyên gia và phòng ban nòng cốt tạo nên giá trị cho GZV.",
    description: "Ban Điều Hành, Ban Cố Vấn và Đội ngũ GZVers đồng hành cùng sự phát triển của hệ sinh thái.",
    button_label: "Xem thêm",
    button_url: "/gioi-thieu",
    sort_order: 50,
    item_limit: 6,
    is_visible: true,
    settings: {
      limitPerDepartment: 6,
      boxes: [
        { title: "BAN ĐIỀU HÀNH", description: "Đội ngũ lãnh đạo và định hướng chiến lược phát triển của GZV Center.", key: "ban_dieu_hanh" },
        { title: "BAN CỐ VẤN", description: "Các chuyên gia đầu ngành trong nhiều lĩnh vực đồng hành cố vấn chuyên môn.", key: "ban_co_van" },
        { title: "ĐỘI NGŨ GZVERS", description: "Những gương mặt trẻ tài năng, nhiệt huyết tham gia triển khai thực tế.", key: "gzvers" },
      ],
    },
  },
  {
    section_key: "partners",
    title: "ĐỐI TÁC",
    subtitle: "ĐỐI TÁC ĐỒNG HÀNH KHẮP CẢ NƯỚC",
    description: "GZV tự hào đồng hành cùng các doanh nghiệp, tổ chức giáo dục và thương hiệu hàng đầu.",
    button_label: "Hợp tác với GZV",
    button_url: "/lien-he",
    sort_order: 60,
    item_limit: 40,
    is_visible: true,
    settings: {
      background: "#ffffff",
    },
  },
  {
    section_key: "news",
    title: "TIN TỨC & BÀI VIẾT MỚI NHẤT",
    subtitle: "Cập nhật những thông tin, sự kiện và bài viết chia sẻ tri thức mới nhất từ GZV.",
    description: "Góc nhìn chuyên sâu, tin tức sự kiện và kiến thức thực chiến từ các chuyên gia.",
    button_label: "Xem tất cả bài viết",
    button_url: "/tin-tuc",
    sort_order: 70,
    item_limit: 6,
    is_visible: true,
    settings: {
      background: "#ffffff",
    },
  },
]

export const fallbackTemplates: SectionTemplate[] = [
  {
    template_key: "hero-stats",
    name: "Hero Sắc Cạnh + Số Liệu (HeroStats)",
    category: "home",
    component_type: "hero_stats",
    default_props: {
      title: "TIÊU ĐỀ TRANG",
      subtitle: "Mô tả ngắn, gọn và sắc nét cho trang.",
      stats: [{ value: "10+", label: "Dự án" }, { value: "5000+", label: "Học viên" }, { value: "50+", label: "Đối tác" }],
      backgroundFrom: "#050505",
      backgroundTo: "#ed1c24",
    },
    sort_order: 1,
    is_active: true,
  },
  {
    template_key: "about-gzv",
    name: "Giới Thiệu GZV (AboutGzv)",
    category: "home",
    component_type: "about_gzv",
    default_props: {
      title: "GZV LTD - HÀNH TRÌNH KIẾN TẠO",
      subtitle: "GZV Center được thành lập với sứ mệnh hỗ trợ và phát triển năng lực lãnh đạo cho thế hệ trẻ.",
      description: "Chúng tôi mang đến các chương trình huấn luyện, tư vấn chiến lược và môi trường trải nghiệm thực chiến.",
      image_url: "/placeholder.jpg",
      button_label: "XEM CÂU CHUYỆN GZV",
      button_url: "/gioi-thieu",
    },
    sort_order: 2,
    is_active: true,
  },
  {
    template_key: "projects-grid",
    name: "Dự Án Tiêu Biểu (ProjectsGrid)",
    category: "home",
    component_type: "projects_grid",
    default_props: {
      title: "DỰ ÁN TIÊU BIỂU",
      subtitle: "Những chiến dịch và dự án tiêu biểu do GZV cùng đối tác triển khai.",
      item_limit: 6,
      button_label: "XEM TẤT CẢ DỰ ÁN",
      button_url: "/du-an",
    },
    sort_order: 3,
    is_active: true,
  },
  {
    template_key: "services-three",
    name: "Dịch Vụ Cung Cấp (ServicesThree)",
    category: "home",
    component_type: "services_three",
    default_props: {
      title: "GIẢI PHÁP ĐÀO TẠO & PHÁT TRIỂN",
      subtitle: "Các gói giải pháp được thiết kế tối ưu cho cá nhân và tổ chức.",
    },
    sort_order: 4,
    is_active: true,
  },
  {
    template_key: "about-boxes",
    name: "Khối Sứ Mệnh & Tầm Nhìn (AboutBoxes)",
    category: "home",
    component_type: "about_boxes",
    default_props: {
      title: "GIÁ TRỊ CỐT LÕI CỦA GZV",
      items: [
        { title: "SỨ MỆNH", description: "Truyền cảm hứng và khai phóng tiềm năng của thế hệ trẻ Việt Nam.", icon: "target" },
        { title: "TẦM NHÌN", description: "Trở thành hệ sinh thái đào tạo & phát triển tư duy hàng đầu.", icon: "eye" },
        { title: "GIÁ TRỊ", description: "Chân thật - Đột phá - Bền vững - Đồng hành.", icon: "award" },
      ],
    },
    sort_order: 5,
    is_active: true,
  },
  {
    template_key: "partners-grid",
    name: "Đối Tác Đồng Hành (PartnersGrid)",
    category: "home",
    component_type: "partners_grid",
    default_props: {
      title: "ĐỐI TÁC ĐỒNG HÀNH KHẮP CẢ NƯỚC",
      subtitle: "GZV tự hào đồng hành cùng các tập đoàn và thương hiệu hàng đầu.",
    },
    sort_order: 6,
    is_active: true,
  },
  {
    template_key: "news-grid",
    name: "Tin Tức & Bài Viết Mới Nhất (NewsGrid)",
    category: "home",
    component_type: "news_grid",
    default_props: {
      title: "TIN TỨC & BÀI VIẾT MỚI NHẤT",
      subtitle: "Cập nhật những thông tin, sự kiện và bài viết chia sẻ tri thức mới nhất từ GZV.",
      item_limit: 3,
      button_label: "XEM TẤT CẢ BÀI VIẾT",
      button_url: "/tin-tuc",
    },
    sort_order: 7,
    is_active: true,
  },
  {
    template_key: "stats-bar",
    name: "Khối Con Số Thống Kê (StatsBar)",
    category: "content",
    component_type: "stats_bar",
    default_props: {
      columns: 4,
      stats: [
        { value: "10+", label: "Năm kinh nghiệm", description: "Đồng hành và phát triển" },
        { value: "5000+", label: "Học viên", description: "Tham gia đào tạo" },
        { value: "50+", label: "Doanh nghiệp", description: "Đối tác chiến lược" },
        { value: "98%", label: "Hài lòng", description: "Đánh giá chất lượng" },
      ],
    },
    sort_order: 8,
    is_active: true,
  },
  {
    template_key: "story-split",
    name: "Câu Chuyện & Hình Ảnh (StorySplit)",
    category: "about",
    component_type: "story_split",
    default_props: {
      title: "CÂU CHUYỆN GZV",
      subtitle: "Hành trình kiến tạo hệ sinh thái Mentoring & Coaching thực chiến",
      body: "GZV Center được thành lập với sứ mệnh kết nối tri thức và phát triển nguồn nhân lực chất lượng cao.",
      image_url: "/gioi-thieu/19.webp",
      button_label: "Khám phá các dự án",
      button_url: "/du-an",
    },
    sort_order: 9,
    is_active: true,
  },
  {
    template_key: "core-showcase",
    name: "Sứ Mệnh & Giá Trị Cốt Lõi (CoreShowcase)",
    category: "about",
    component_type: "core_showcase",
    default_props: {
      title: "SỨ MỆNH. TẦM NHÌN. GIÁ TRỊ CỐT LÕI.",
      subtitle: "GZV định hình một hệ sinh thái triển khai thực chiến.",
      highlights: ["Thực chiến", "Minh bạch", "Tăng trưởng"],
      items: [
        { label: "01", title: "Sứ mệnh", description: "Kết nối tri thức, chuyên gia và doanh nghiệp." },
        { label: "02", title: "Tầm nhìn", description: "Trở thành hệ sinh thái mentoring và coaching hàng đầu." },
        { label: "03", title: "Giá trị cốt lõi", description: "Thực chiến, minh bạch và tạo tác động thật." },
      ],
    },
    sort_order: 10,
    is_active: true,
  },
  {
    template_key: "timeline-block",
    name: "Hành Trình Phát Triển (TimelineBlock)",
    category: "about",
    component_type: "timeline",
    default_props: {
      title: "HÀNH TRÌNH PHÁT TRIỂN",
      subtitle: "Những cột mốc quan trọng của GZV Center qua từng năm",
      items: [
        { year: "2018", title: "Khởi đầu sứ mệnh", description: "Thành lập cộng đồng chia sẻ tri thức đầu tiên." },
        { year: "2020", title: "Mở rộng hệ sinh thái", description: "Chuẩn hóa mô hình Mentoring & Coaching 1:1." },
        { year: "2022", title: "Đột phá chuyển đổi số", description: "Tư vấn chiến lược cho doanh nghiệp SMEs." },
        { year: "2024+", title: "Vươn tầm phát triển", description: "Đạt mốc 10.000+ học viên và 100+ đối tác." },
      ],
    },
    sort_order: 11,
    is_active: true,
  },
  {
    template_key: "mentoring-model",
    name: "Mô Hình Triển Khai 70-20-10 (MentoringModel)",
    category: "about",
    component_type: "mentoring_model",
    default_props: {
      title: "MÔ HÌNH TRIỂN KHAI",
      subtitle: "Phương pháp đào tạo và đồng hành thực chiến chuẩn quốc tế",
      steps: [
        { title: "70% Thực hành thực tế", description: "Trực tiếp tham gia giải quyết các bài toán thực tế." },
        { title: "20% Học hỏi từ Mentor", description: "Được hướng dẫn kèm cặp 1:1 từ chuyên gia." },
        { title: "10% Kiến thức nền tảng", description: "Hệ thống hóa kiến thức chuyên sâu chuẩn xác." },
      ],
    },
    sort_order: 12,
    is_active: true,
  },
  {
    template_key: "people-grid",
    name: "Ban Điều Hành & Cố Vấn (PeopleGrid)",
    category: "about",
    component_type: "people_grid",
    default_props: {
      title: "BAN ĐIỀU HÀNH & CỐ VẤN",
      subtitle: "Đội ngũ lãnh đạo tâm huyết dẫn dắt tổ chức",
      type: "directors",
      limit: 6,
    },
    sort_order: 13,
    is_active: true,
  },
  {
    template_key: "feature-grid-red",
    name: "Lưới Giá Trị / Tính Năng (FeatureGrid)",
    category: "content",
    component_type: "feature_grid",
    default_props: {
      title: "GIÁ TRỊ NỔI BẬT",
      subtitle: "Các điểm mạnh có thể thêm, xóa, sửa trực tiếp trong props.",
      columns: 3,
      items: [
        { title: "Tư duy chiến lược", description: "Mô tả ngắn cho giá trị này.", icon: "target", color: "#ed1c24" },
        { title: "Triển khai thực chiến", description: "Mô tả ngắn cho giá trị này.", icon: "book", color: "#050505" },
        { title: "Đo lường kết quả", description: "Mô tả ngắn cho giá trị này.", icon: "award", color: "#ed1c24" },
      ],
    },
    sort_order: 10,
    is_active: true,
  },
  {
    template_key: "gallery-editor",
    name: "Bộ Ảnh Thư Viện (ImageGallery)",
    category: "media",
    component_type: "image_gallery",
    default_props: {
      title: "THƯ VIỆN HÌNH ẢNH",
      subtitle: "Quản lý từng ảnh, tiêu đề, mô tả và phân loại.",
      images: [
        { src: "/placeholder.jpg", title: "Ảnh 1", category: "GZV", description: "Mô tả ảnh", alt: "GZV" },
        { src: "/placeholder.jpg", title: "Ảnh 2", category: "GZV", description: "Mô tả ảnh", alt: "GZV" },
      ],
    },
    sort_order: 11,
    is_active: true,
  },
  {
    template_key: "rich-content",
    name: "Khối Nội Dung Rich Text (HtmlBlock)",
    category: "content",
    component_type: "html_rich",
    default_props: { maxWidth: "980px" },
    sort_order: 12,
    is_active: true,
  },
  {
    template_key: "contact-layout",
    name: "Form + Thông Tin Liên Hệ",
    category: "contact",
    component_type: "contact_form",
    default_props: {
      info_title: "THÔNG TIN LIÊN HỆ",
      info_subtitle: "Phản hồi nhanh trong vòng 24 giờ làm việc.",
      form_title: "GỬI TIN NHẮN",
      form_description: "Chúng tôi sẽ phản hồi qua email bạn cung cấp.",
      submit_label: "GỬI TIN NHẮN",
      success_message: "Cảm ơn bạn! Tin nhắn đã được gửi thành công. Chúng tôi sẽ phản hồi sớm nhất.",
      email: "vsm.org.vn@gmail.com",
      phone: "0329 381 489",
      address: "139 Nguyễn Thị Thập, Tân Hưng, Q.7, TP.HCM",
      working_hours: "Thứ 2 – Thứ 6: 8:00 – 18:00",
      social_facebook: "https://www.facebook.com/gzv.one",
      social_youtube: "https://youtube.com",
    },
    sort_order: 13,
    is_active: true,
  },
  {
    template_key: "google-map",
    name: "Bản Đồ Google Map (GoogleMapBlock)",
    category: "contact",
    component_type: "google_map",
    default_props: {
      title: "Tìm chúng tôi trên bản đồ",
      address: "230/5/10 Vĩnh Viễn, Phường Vườn Lài, TP. HCM",
      map_embed_url: "https://maps.google.com/maps?q=230/5/10%20V%C4%A9nh%20Vi%E1%BB%85n%2C%20Ph%C6%B0%E1%BB%9Dng%20V%C6%B0%E1%BB%9Dn%20L%C3%A0i%2C%20TP.%20HCM&t=&z=16&ie=UTF8&iwloc=&output=embed",
      height: "medium",
      map_enabled: true,
    },
    sort_order: 14,
    is_active: true,
  },
]

export const defaultNav: NavItem[] = [
  { href: "/", label_vi: "TRANG CHỦ", label_en: "HOME", sort_order: 5, is_visible: true, is_page_enabled: true },
  { href: "/gioi-thieu", label_vi: "GIỚI THIỆU", label_en: "ABOUT", sort_order: 10, is_visible: true, is_page_enabled: true },
  {
    href: "/dich-vu",
    label_vi: "DỊCH VỤ",
    label_en: "SERVICES",
    sort_order: 20,
    is_visible: true,
    is_page_enabled: true,
    children: [
      { href: "/dich-vu/marketing", label_vi: "MARKETING", label_en: "MARKETING", parent_href: "/dich-vu", sort_order: 10, is_visible: true, is_page_enabled: true },
      { href: "/cua-hang", label_vi: "CỬA HÀNG", label_en: "STORE", parent_href: "/dich-vu", sort_order: 20, is_visible: true, is_page_enabled: true },
    ],
  },
  { href: "/du-an", label_vi: "DỰ ÁN", label_en: "PROJECTS", sort_order: 30, is_visible: true, is_page_enabled: true },
  { href: "/gzver", label_vi: "GZVers", label_en: "GZVers", sort_order: 40, is_visible: true, is_page_enabled: true },
  { href: "/doi-tac", label_vi: "ĐỐI TÁC", label_en: "PARTNERS", sort_order: 45, is_visible: true, is_page_enabled: true },
  { href: "/tin-tuc", label_vi: "TIN TỨC", label_en: "NEWS", sort_order: 50, is_visible: true, is_page_enabled: true },
  { href: "/lien-he", label_vi: "LIÊN HỆ", label_en: "CONTACT", sort_order: 60, is_visible: true, is_page_enabled: true },
]

export const quickBuilderPages = [
  { slug: "dich-vu", label: "Dịch vụ", hint: "Trang riêng /dich-vu" },
  { slug: "gioi-thieu", label: "Giới thiệu", hint: "Câu chuyện, sứ mệnh, tầm nhìn" },
  { slug: "du-an", label: "Dự án", hint: "Banner, block dự án" },
  { slug: "gzver", label: "GZVers", hint: "Cộng đồng, ban, profile" },
  { slug: "tin-tuc", label: "Tin tức", hint: "Banner và block nội dung tin" },
  { slug: "lien-he", label: "Liên hệ", hint: "Form, map, thông tin liên hệ" },
]

export const defaultLoading: LoadingSettings = { id: 1, logo_url: "/logo.webp", title: "GZV", subtitle: "Đang tải dữ liệu...", effect: "orbit", background_from: "#050505", background_to: "#ed1c24", accent_color: "#ed1c24", enabled: false, minimum_duration_ms: 900 }
export const defaultBranding: BrandingSettings = { id: 1, site_name: "GZV", header_logo_url: "/logo.webp", footer_logo_url: "/logo.webp", favicon_url: "/logo/favicon.ico", default_title: "GZV - The Voice of Genzers", title_template: "%s | GZV", default_description: "GZV Center", default_keywords: "GZV, đào tạo, mentoring, coaching", og_image_url: "/og-image.jpg", topbar_email_label: "gzv.one@gmail.com", topbar_phone_label: "(+84) 329 381 489", topbar_badge_label: "GZV" }
export const defaultFooter: FooterSettings = {
  id: 1,
  logo_url: "/logo.webp",
  intro_text: "GZV - The Voice of Genzers",
  background_color: "#050505",
  bottom_background_color: "#111111",
  facebook_page_url: "https://www.facebook.com/gzv.one",
  address: "279 Nguyễn Tri Phương, Phường Diên Hồng, TP.Hồ Chí Minh",
  phone_label: "Điện Thoại: (+84) 329 381 489",
  phone_url: "tel:+84329381489",
  email_label: "Email: gzv.one@gmail.com",
  email_url: "mailto:gzv.one@gmail.com",
  newsletter_title: "Kết nối với chúng tôi",
  newsletter_description: "Đăng ký để nhận thông tin về các khóa học và sự kiện mới nhất.",
  copyright_text: "gzv Center. Phát triển bởi Phòng Công nghệ thông tin.",
  links: [],
  social_links: [],
}

export const defaultBannerConfig = {
  badge: "GZV CENTER",
  title: "TIÊU ĐỀ BÌA CỦA TRANG",
  subtitle: "Mô tả ngắn gọn sắc nét cho banner trang",
  use_image: true,
  cover_url: "/placeholder.jpg",
  imagePositionY: "50%",
  image_opacity: 100,
  image_grayscale: false,
  overlay_enabled: true,
  overlay_color: "#050505",
  overlay_opacity: 60,
  bg_color: "#050505",
  bg_from: "#050505",
  bg_to: "#ed1c24",
  titleAlignment: "center" as "left" | "center" | "right",
  show_badge: true,
  show_title: true,
  show_subtitle: true,
  badge_color: "#ffffff",
  title_color: "#ffffff",
  subtitle_color: "rgba(255,255,255,0.85)",
}

export const defaultPageBlocks: PageBlock[] = [
  // 1. Dịch vụ (/dich-vu)
  {
    page_slug: "dich-vu",
    block_key: "stats",
    component_type: "stats_bar",
    title: "CON SỐ THỐNG KÊ DỊCH VỤ",
    props: {
      columns: 4,
      stats: [
        { value: "3", label: "Mũi triển khai", description: "Marketing, Sales, Chuyển đổi số" },
        { value: "50+", label: "Đối tác", description: "Doanh nghiệp đồng hành" },
        { value: "10+", label: "Lĩnh vực", description: "Kinh nghiệm thực tiễn" },
        { value: "100%", label: "Thực chiến", description: "Tập trung vào kết quả" },
      ],
    },
    sort_order: 10,
    is_visible: true,
  },
  {
    page_slug: "dich-vu",
    block_key: "services",
    component_type: "services_three",
    title: "SERVICES",
    props: {
      title: "SERVICES",
      subtitle: "Marketing | Sales | Digital Transformation",
      items: [
        { title: "Marketing", icon: "megaphone", description: "Xây dựng chiến lược thương hiệu, nội dung, chiến dịch tăng trưởng và truyền thông đa kênh." },
        { title: "Sales", icon: "trend", description: "Thiết kế pipeline, kịch bản bán hàng, đào tạo đội ngũ và tối ưu chuyển đổi doanh thu." },
        { title: "Digital Transformation", icon: "cpu", description: "Chuẩn hóa quy trình, dữ liệu, tự động hóa và công cụ vận hành cho doanh nghiệp." },
      ],
    },
    sort_order: 20,
    is_visible: true,
  },
  {
    page_slug: "dich-vu",
    block_key: "mentoring_model",
    component_type: "mentoring_model",
    title: "QUY TRÌNH TRIỂN KHAI",
    props: {
      title: "QUY TRÌNH TRIỂN KHAI",
      subtitle: "Lộ trình đồng hành thực chiến cùng doanh nghiệp",
    },
    sort_order: 30,
    is_visible: true,
  },
  {
    page_slug: "dich-vu",
    block_key: "why_columns",
    component_type: "why_columns",
    title: "TẠI SAO CHỌN GZV",
    props: {
      title: "TẠI SAO CHỌN GZV",
      subtitle: "Khác biệt tạo nên hiệu quả",
    },
    sort_order: 40,
    is_visible: true,
  },
  {
    page_slug: "dich-vu",
    block_key: "cta",
    component_type: "cta_band",
    title: "SẴN SÀNG TRAO ĐỔI BÀI TOÁN TĂNG TRƯỜNG",
    props: {
      title: "SẴN SÀNG TRAO ĐỔI BÀI TOÁN TĂNG TRƯỜNG",
      subtitle: "Gửi thông tin để đội ngũ GZV tư vấn hướng triển khai phù hợp nhất.",
      button_label: "Đăng ký tư vấn ngay",
      button_url: "/lien-he",
      background_from: "#050505",
      background_to: "#ed1c24",
    },
    sort_order: 50,
    is_visible: true,
  },

  // 2. Giới thiệu (/gioi-thieu)
  {
    page_slug: "gioi-thieu",
    block_key: "stats",
    component_type: "stats_bar",
    title: "CON SỐ ẤN TƯỢNG GZV",
    props: {
      columns: 4,
      stats: [
        { value: "50+", label: "Doanh nghiệp", description: "Đối tác chiến lược" },
        { value: "5000+", label: "Học viên", description: "Tham gia các khóa đào tạo" },
        { value: "100+", label: "Mentor & Chuyên gia", description: "Mạng lưới cố vấn thực chiến" },
        { value: "95%", label: "Tỷ lệ hài lòng", description: "Đánh giá chất lượng đào tạo" },
      ],
    },
    sort_order: 10,
    is_visible: true,
  },
  {
    page_slug: "gioi-thieu",
    block_key: "story",
    component_type: "story_split",
    title: "Câu chuyện GZV",
    props: {
      eyebrow: "Câu chuyện GZV",
      title: "CÂU CHUYỆN GZV",
      subtitle: "Từ một cộng đồng học hỏi đến hệ sinh thái triển khai thực chiến.",
      body: "GZV được xây dựng để kết nối thế hệ trẻ, chuyên gia và doanh nghiệp trong cùng một môi trường học tập - làm thật - tạo tác động thật. Chúng tôi tin rằng năng lực chỉ bền vững khi được rèn trong dự án thực tế, dưới sự đồng hành của những người có kinh nghiệm.",
      image_url: "/gioi-thieu/19.webp",
      image_alt: "Câu chuyện GZV",
      position_x: 50,
      position_y: 50,
      image_size: 100,
      stats: [
        { value: "50+", label: "Doanh nghiệp" },
        { value: "5000+", label: "Học viên" },
        { value: "10+", label: "Lĩnh vực" },
      ],
    },
    sort_order: 20,
    is_visible: true,
  },
  {
    page_slug: "gioi-thieu",
    block_key: "mission",
    component_type: "feature_grid",
    title: "Sứ mệnh",
    props: {
      title: "SỨ MỆNH",
      subtitle: "Kết nối tri thức, chuyên gia và doanh nghiệp để tạo năng lực tăng trưởng có thể đo lường.",
      columns: 1,
      items: [
        {
          title: "Tạo năng lực thực chiến",
          description: "GZV giúp người trẻ và doanh nghiệp phát triển thông qua mentoring, coaching và dự án thực tế.",
          icon: "target",
          color: "#ed1c24",
        },
      ],
    },
    sort_order: 30,
    is_visible: true,
  },
  {
    page_slug: "gioi-thieu",
    block_key: "vision",
    component_type: "feature_grid",
    title: "Tầm nhìn",
    props: {
      title: "TẦM NHÌN",
      subtitle: "Trở thành hệ sinh thái mentoring, coaching và triển khai dự án thế hệ mới tại Việt Nam.",
      columns: 1,
      items: [
        {
          title: "Hệ sinh thái Next-Gen",
          description: "Xây dựng mạng lưới chuyên gia, GZVers và đối tác cùng tạo giá trị bền vững.",
          icon: "compass",
          color: "#050505",
        },
      ],
    },
    sort_order: 40,
    is_visible: true,
  },
  {
    page_slug: "gioi-thieu",
    block_key: "core-values",
    component_type: "feature_grid",
    title: "Giá trị cốt lõi",
    props: {
      title: "GIÁ TRỊ CỐT LÕI",
      subtitle: "Những nguyên tắc giúp GZV vận hành sắc cạnh và đáng tin cậy.",
      columns: 4,
      items: [
        {
          title: "Thực chiến",
          description: "Tập trung vào kết quả và bài toán thật.",
          icon: "rocket",
          color: "#ed1c24",
        },
        {
          title: "Minh bạch",
          description: "Rõ mục tiêu, rõ dữ liệu, rõ trách nhiệm.",
          icon: "shield",
          color: "#050505",
        },
        {
          title: "Học hỏi liên tục",
          description: "Luôn cải tiến từ phản hồi và thực nghiệm.",
          icon: "book",
          color: "#ed1c24",
        },
        {
          title: "Tạo tác động",
          description: "Ưu tiên giá trị đo lường được cho cộng đồng và đối tác.",
          icon: "award",
          color: "#050505",
        },
      ],
    },
    sort_order: 50,
    is_visible: true,
  },
  {
    page_slug: "gioi-thieu",
    block_key: "directors",
    component_type: "people_grid",
    title: "Ban điều hành",
    props: {
      eyebrow: "Leadership",
      title: "BAN ĐIỀU HÀNH",
      subtitle: "Lấy dữ liệu tự động từ GZVers đã đánh dấu ban điều hành.",
      type: "directors",
      limit: 6,
    },
    sort_order: 60,
    is_visible: true,
  },
  {
    page_slug: "gioi-thieu",
    block_key: "timeline",
    component_type: "timeline",
    title: "Lộ trình phát triển của GZV",
    props: {
      eyebrow: "Growth Roadmap",
      title: "LỘ TRÌNH PHÁT TRIỂN CỦA GZV",
      subtitle: "Các chặng phát triển được thiết kế để mở rộng năng lực cộng đồng và năng lực triển khai.",
      items: [
        { year: "Giai đoạn 1", title: "Xây nền cộng đồng", description: "Kết nối GZVers, mentor và doanh nghiệp đối tác." },
        { year: "Giai đoạn 2", title: "Chuẩn hóa mô hình", description: "Hoàn thiện mentoring, coaching và project-based learning." },
        { year: "Giai đoạn 3", title: "Triển khai dự án", description: "Đưa đội ngũ vào các bài toán Marketing, Sales, Digital Transformation." },
        { year: "Giai đoạn 4", title: "Mở rộng hệ sinh thái", description: "Phát triển mạng lưới đối tác, chuyên gia và dự án liên ngành." },
      ],
    },
    sort_order: 70,
    is_visible: true,
  },
  {
    page_slug: "gioi-thieu",
    block_key: "mentoring-model",
    component_type: "mentoring_model",
    title: "Mô hình Mentoring",
    props: {
      eyebrow: "Mentoring Model",
      title: "MÔ HÌNH MENTORING",
      subtitle: "GZV kết hợp định hướng cá nhân, huấn luyện kỹ năng và triển khai dự án thật.",
      steps: [
        { title: "Đánh giá năng lực", description: "Xác định điểm mạnh, mục tiêu và khoảng trống kỹ năng." },
        { title: "Mentoring cá nhân hóa", description: "Kết nối mentor phù hợp để định hướng lộ trình phát triển." },
        { title: "Dự án thực chiến", description: "Thực hành trên bài toán thật để tạo năng lực có thể đo lường." },
      ],
    },
    sort_order: 80,
    is_visible: true,
  },
  {
    page_slug: "gioi-thieu",
    block_key: "cta",
    component_type: "cta_band",
    title: "KẾT NỐI VỚI GZV",
    props: {
      title: "ĐỒNG HÀNH CÙNG GZV",
      subtitle: "Hãy cùng chúng tôi kiến tạo những giá trị mới cho doanh nghiệp và sự nghiệp của bạn.",
      button_label: "Liên hệ ngay",
      button_url: "/lien-he",
      background_from: "#050505",
      background_to: "#ed1c24",
    },
    sort_order: 90,
    is_visible: true,
  },

  // 3. Dự án (/du-an)
  {
    page_slug: "du-an",
    block_key: "stats",
    component_type: "stats_bar",
    title: "THỐNG KÊ DỰ ÁN",
    props: {
      columns: 4,
      stats: [
        { value: "10+", label: "Dự án tiêu biểu", description: "Quy mô thực tế" },
        { value: "50+", label: "Doanh nghiệp", description: "Đồng hành phát triển" },
        { value: "5000+", label: "Học viên", description: "Tham gia đào tạo" },
        { value: "10+", label: "Lĩnh vực", description: "Kinh nghiệm đa ngành" },
      ],
    },
    sort_order: 10,
    is_visible: true,
  },
  {
    page_slug: "du-an",
    block_key: "projects",
    component_type: "projects_grid",
    title: "DANH SÁCH DỰ ÁN",
    props: {
      title: "DỰ ÁN ĐÃ TRIỂN KHAI",
      subtitle: "Những chiến dịch và dự án tiêu biểu do GZV cùng đối tác triển khai",
      show_search: true,
      show_categories: true,
      limit: 12,
    },
    sort_order: 20,
    is_visible: true,
  },
  {
    page_slug: "du-an",
    block_key: "cta",
    component_type: "cta_band",
    title: "KÊU GỌI HÀNH ĐỘNG (CTA)",
    props: {
      title: "Bạn có dự án cần triển khai?",
      subtitle: "Hãy để GZV Center trở thành đối tác đồng hành, thiết kế chương trình đào tạo riêng biệt và hiệu quả cho tổ chức của bạn.",
      button_label: "Liên hệ ngay",
      button_url: "/lien-he",
      background_from: "#050505",
      background_to: "#ed1c24",
    },
    sort_order: 30,
    is_visible: true,
  },

  // 4. GZVers (/gzver)
  {
    page_slug: "gzver",
    block_key: "stats",
    component_type: "stats_bar",
    title: "QUY MÔ NHÂN SỰ",
    props: {
      columns: 4,
      stats: [
        { value: "50+", label: "GZVers", description: "Nhân sự trẻ trung, nhiệt huyết" },
        { value: "10+", label: "Cố vấn & Mentor", description: "Chuyên gia đầu ngành" },
        { value: "5+", label: "Ban chuyên môn", description: "Vận hành chuyên nghiệp" },
        { value: "100%", label: "Thực chiến", description: "Cam kết đồng hành" },
      ],
    },
    sort_order: 10,
    is_visible: true,
  },
  {
    page_slug: "gzver",
    block_key: "gzvers_list",
    component_type: "gzvers_grid",
    title: "ĐỘI NGŨ NHÂN SỰ GZV",
    props: {
      title: "ĐỘI NGŨ NHÂN SỰ GZV",
      subtitle: "Đội ngũ nhân sự, cố vấn và chuyên gia đồng hành",
    },
    sort_order: 20,
    is_visible: true,
  },
  {
    page_slug: "gzver",
    block_key: "cta",
    component_type: "cta_band",
    title: "GIA NHẬP GZV",
    props: {
      title: "Gia nhập đại gia đình GZV",
      subtitle: "Trở thành một phần của cộng đồng trẻ năng động, sáng tạo và bứt phá giới hạn.",
      button_label: "Ứng tuyển ngay",
      button_url: "/lien-he",
      background_from: "#050505",
      background_to: "#ed1c24",
    },
    sort_order: 30,
    is_visible: true,
  },

  // 5. Đối tác (/doi-tac)
  {
    page_slug: "doi-tac",
    block_key: "stats",
    component_type: "stats_bar",
    title: "MẠNG LƯỚI TOÀN CẦU",
    props: {
      columns: 4,
      stats: [
        { value: "100+", label: "Đối tác doanh nghiệp", description: "Tập đoàn & Doanh nghiệp hàng đầu" },
        { value: "50+", label: "Trường ĐH & Viện", description: "Hợp tác đào tạo và nghiên cứu" },
        { value: "5000+", label: "Học viên", description: "Được đào tạo và kết nối việc làm" },
        { value: "100%", label: "Thực chiến", description: "Cam kết đồng hành & phát triển" },
      ],
    },
    sort_order: 10,
    is_visible: true,
  },
  {
    page_slug: "doi-tac",
    block_key: "partners_list",
    component_type: "partners_grid",
    title: "MẠNG LƯỚI ĐỐI TÁC CHIẾN LƯỢC",
    props: {
      title: "MẠNG LƯỚI ĐỐI TÁC CHIẾN LƯỢC",
      subtitle: "Đồng hành cùng các tập đoàn, doanh nghiệp và viện trường hàng đầu kiến tạo giá trị thực chiến",
      show_filter: true,
    },
    sort_order: 20,
    is_visible: true,
  },
  {
    page_slug: "doi-tac",
    block_key: "cta",
    component_type: "cta_band",
    title: "HỢP TÁC CÙNG GZV",
    props: {
      title: "Đồng hành & Phát triển cùng GZV",
      subtitle: "Kết nối nguồn nhân lực chất lượng cao, triển khai dự án thực chiến và mở rộng mạng lưới kinh doanh.",
      button_label: "Liên hệ hợp tác ngay",
      button_url: "/lien-he",
      background_from: "#050505",
      background_to: "#ed1c24",
    },
    sort_order: 30,
    is_visible: true,
  },

  // 6. Tin tức (/tin-tuc)
  {
    page_slug: "tin-tuc",
    block_key: "stats",
    component_type: "stats_bar",
    title: "THỐNG KÊ TRI THỨC",
    props: {
      columns: 4,
      stats: [
        { value: "100+", label: "Bài viết chuyên sâu", description: "Cập nhật liên tục" },
        { value: "10+", label: "Chuyên mục", description: "Marketing, Sales, Tech, v.v." },
        { value: "50K+", label: "Lượt đọc", description: "Độc giả theo dõi hàng tháng" },
        { value: "24/7", label: "Cập nhật", description: "Xu hướng thị trường mới nhất" },
      ],
    },
    sort_order: 10,
    is_visible: true,
  },
  {
    page_slug: "tin-tuc",
    block_key: "news_list",
    component_type: "news_grid",
    title: "DANH SÁCH TIN TỨC",
    props: {
      title: "TIN TỨC MỚI NHẤT",
      subtitle: "Tổng hợp các bài viết nổi bật, xu hướng ngành và hoạt động của GZV",
      limit: 9,
      show_categories: true,
    },
    sort_order: 20,
    is_visible: true,
  },
  {
    page_slug: "tin-tuc",
    block_key: "cta",
    component_type: "cta_band",
    title: "BẢN TIN GZV",
    props: {
      title: "Đăng ký nhận bản tin GZV",
      subtitle: "Nhận các bài viết chuyên sâu và xu hướng thị trường hàng tuần từ đội ngũ chuyên gia.",
      button_label: "Đăng ký ngay",
      button_url: "/lien-he",
      background_from: "#050505",
      background_to: "#ed1c24",
    },
    sort_order: 30,
    is_visible: true,
  },

  // 6. Mentors (/mentors)
  {
    page_slug: "mentors",
    block_key: "stats",
    component_type: "stats_bar",
    title: "THỐNG KÊ BAN GIẢNG HUẤN",
    props: {
      columns: 4,
      stats: [
        { value: "50+", label: "Chuyên gia & Mentor", description: "Đầu ngành thực chiến" },
        { value: "15+", label: "Năm kinh nghiệm TB", description: "Thực tế tại doanh nghiệp" },
        { value: "30+", label: "Lĩnh vực chuyên môn", description: "Đa ngành đa lĩnh vực" },
        { value: "100%", label: "Tâm huyết", description: "Đồng hành sát cánh" },
      ],
    },
    sort_order: 10,
    is_visible: true,
  },
  {
    page_slug: "mentors",
    block_key: "mentors_list",
    component_type: "mentors_grid",
    title: "DANH SÁCH MENTORS",
    props: {
      title: "BAN GIẢNG HUẤN & CỐ VẤN",
      subtitle: "Gặp gỡ đội ngũ giảng huấn giàu kinh nghiệm thực chiến",
      limit: 12,
    },
    sort_order: 20,
    is_visible: true,
  },
  {
    page_slug: "mentors",
    block_key: "cta",
    component_type: "cta_band",
    title: "KẾT NỐI MENTOR",
    props: {
      title: "Đồng hành cùng Mentor GZV",
      subtitle: "Đăng ký để được kết nối và tham gia các chương trình đào tạo chuyên sâu.",
      button_label: "Nhận tư vấn ngay",
      button_url: "/lien-he",
      background_from: "#050505",
      background_to: "#ed1c24",
    },
    sort_order: 30,
    is_visible: true,
  },

  // 7. Liên hệ (/lien-he)
  {
    page_slug: "lien-he",
    block_key: "stats",
    component_type: "stats_bar",
    title: "KÊNH KẾT NỐI",
    props: {
      columns: 4,
      stats: [
        { value: "24h", label: "Phản hồi tối đa", description: "Tiếp nhận thông tin nhanh" },
        { value: "100%", label: "Tận tâm", description: "Tư vấn đúng bài toán" },
        { value: "Free", label: "Tư vấn ban đầu", description: "Đánh giá nhu cầu miễn phí" },
        { value: "1:1", label: "Chuyên gia", description: "Đồng hành trực tiếp" },
      ],
    },
    sort_order: 10,
    is_visible: true,
  },
  {
    page_slug: "lien-he",
    block_key: "contact_block",
    component_type: "contact_form",
    title: "FORM LIÊN HỆ & THÔNG TIN",
    props: {
      info_title: "THÔNG TIN LIÊN HỆ",
      info_subtitle: "Phản hồi nhanh trong vòng 24 giờ làm việc.",
      form_title: "GỬI TIN NHẮN",
      form_description: "Chúng tôi sẽ phản hồi qua email bạn cung cấp.",
      submit_label: "GỬI TIN NHẮN",
      success_message: "Cảm ơn bạn! Tin nhắn đã được gửi thành công. Chúng tôi sẽ phản hồi sớm nhất.",
      email: "vsm.org.vn@gmail.com",
      phone: "0329 381 489",
      address: "139 Nguyễn Thị Thập, Tân Hưng, Q.7, TP.HCM",
      working_hours: "Thứ 2 – Thứ 6: 8:00 – 18:00",
      social_facebook: "https://www.facebook.com/gzv.one",
      social_youtube: "https://youtube.com",
      map_title: "Tìm chúng tôi trên bản đồ",
      map_embed_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.917155214181!2d106.69327317583824!3d10.740868259846957!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752fa1667d22ef%3A0x9146408a220f7abf!2zMTM5IMSQLiBOZ3V54buFbiBUaOG7iyBUaOG6rXAsIEtodSDEkcO0IHRo4buLIEhpbSBMYW0sIFTDom4gSMawbmcsIEjhu5MgQ2jDrSBNaW5oLCBWaWV0bmFt!5e0!3m2!1sen!2s!4v1777740146485!5m2!1sen!2s",
      map_enabled: true,
    },
    sort_order: 20,
    is_visible: true,
  },
]

export function normalizeSlug(str: string) {
  return str
    .toLowerCase()
    .trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\u0111/g, "d")
    .replace(/\u0110/g, "d")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
}
