import type {
  HomeSection,
  SectionTemplate,
  NavItem,
  LoadingSettings,
  BrandingSettings,
  FooterSettings,
  PageBlock,
} from "./types"

export const defaultHomeSections: HomeSection[] = [
  {
    section_key: "hero",
    title: "GZV Ltd",
    subtitle: "The Next-Gen Company",
    description: "Đồng hành cùng doanh nghiệp và thế hệ trẻ qua Marketing, Sales và Digital Transformation với tư duy triển khai thực chiến.",
    button_label: "Khám phá dịch vụ",
    button_url: "/dich-vu",
    sort_order: 10,
    item_limit: 1,
    is_visible: true,
    settings: {
      video_url: "/Intro.mp4",
    },
  },
  {
    section_key: "about_gzv",
    title: "CÂU CHUYỆN GZV",
    subtitle: "Từ một cộng đồng học hỏi đến hệ sinh thái triển khai thực chiến.",
    description: "GZV được xây dựng để kết nối thế hệ trẻ, chuyên gia và doanh nghiệp trong cùng một môi trường học tập - làm thật - tạo tác động thật. Chúng tôi tin rằng năng lực chỉ bền vững khi được rèn trong dự án thực tế, dưới sự đồng hành của những người có kinh nghiệm.",
    button_label: "Xem chi tiết",
    button_url: "/gioi-thieu",
    sort_order: 20,
    item_limit: 1,
    is_visible: true,
    settings: {
      eyebrow: "GIỚI THIỆU",
      image_url: "/gioi-thieu/19.webp",
      image_alt: "GZV",
      position_x: 50,
      position_y: 50,
      image_size: 100,
      button_label: "Xem chi tiết",
      button_url: "/gioi-thieu",
    },
  },
  {
    section_key: "projects",
    title: "DỰ ÁN ĐÃ TRIỂN KHAI",
    subtitle: "Những chiến dịch và dự án tiêu biểu do GZV cùng đối tác triển khai",
    description: "Danh sách các dự án thực chiến đã mang lại giá trị đo lường được cho doanh nghiệp.",
    button_label: "Xem tất cả dự án",
    button_url: "/du-an",
    sort_order: 30,
    item_limit: 6,
    is_visible: true,
    settings: {
      background: "#ffffff",
    },
  },
  {
    section_key: "services_three",
    title: "SERVICES",
    subtitle: "Marketing | Sales | Digital Transformation | Education | Events",
    description: "Giải pháp đào tạo, tư vấn và triển khai thực chiến cho cá nhân & doanh nghiệp.",
    button_label: "Xem tất cả dịch vụ",
    button_url: "/dich-vu",
    sort_order: 40,
    item_limit: 3,
    is_visible: true,
    settings: {
      services: [
        { title: "MARKETING & BRANDING", description: "Đào tạo thực chiến & tư vấn chiến lược marketing tổng thể, phát triển thương hiệu đa kênh.", link: "/dich-vu/marketing", icon: "megaphone" },
        { title: "SALES & PHÁT TRIỂN DOANH SỐ", description: "Xây dựng quy trình bán hàng, tối ưu hóa tỷ lệ chuyển đổi và mở rộng thị trường.", link: "/dich-vu", icon: "trend" },
        { title: "DIGITAL TRANSFORMATION", description: "Ứng dụng công nghệ, AI và tự động hóa quy trình vận hành doanh nghiệp hiệu quả.", link: "/dich-vu", icon: "cpu" },
      ],
    },
  },
  {
    section_key: "about_boxes",
    title: "VỀ CHÚNG TÔI",
    subtitle: "Đội ngũ nhân sự, chuyên gia và phòng ban nòng cốt tạo nên giá trị cho GZV.",
    description: "Ban Điều Hành, Ban Cố Vấn và Đội ngũ GZVers đồng hành cùng sự phát triển của hệ sinh thái.",
    button_label: "Xem thêm",
    button_url: "/gioi-thieu",
    sort_order: 50,
    item_limit: 6,
    is_visible: true,
    settings: {
      limitPerDepartment: 6,
      boxes: [
        { title: "BAN ĐIỀU HÀNH", description: "Đội ngũ lãnh đạo và định hướng chiến lược phát triển của GZV Center.", key: "ban_dieu_hanh" },
        { title: "BAN CỐ VẤN", description: "Các chuyên gia đầu ngành trong nhiều lĩnh vực đồng hành cố vấn chuyên môn.", key: "ban_co_van" },
        { title: "ĐỘI NGŨ GZVERS", description: "Những gương mặt trẻ tài năng, nhiệt huyết tham gia triển khai thực tế.", key: "gzvers" },
      ],
    },
  },
  {
    section_key: "partners",
    title: "ĐỐI TÁC",
    subtitle: "ĐỐI TÁC ĐỒNG HÀNH KHẮP CẢ NƯỚC",
    description: "GZV tự hào đồng hành cùng các doanh nghiệp, tổ chức giáo dục và thương hiệu hàng đầu.",
    button_label: "Hợp tác với GZV",
    button_url: "/lien-he",
    sort_order: 60,
    item_limit: 40,
    is_visible: true,
    settings: {
      background: "#ffffff",
    },
  },
  {
    section_key: "news",
    title: "TIN TỨC & BÀI VIẾT MỚI NHẤT",
    subtitle: "Cập nhật những thông tin, sự kiện và bài viết chia sẻ tri thức mới nhất từ GZV.",
    description: "Góc nhìn chuyên sâu, tin tức sự kiện và kiến thức thực chiến từ các chuyên gia.",
    button_label: "Xem tất cả bài viết",
    button_url: "/tin-tuc",
    sort_order: 70,
    item_limit: 6,
    is_visible: true,
    settings: {
      background: "#ffffff",
    },
  },
]

export const fallbackTemplates: SectionTemplate[] = [
  {
    template_key: "hero-stats",
    name: "Hero Sắc Cạnh + Số Liệu (HeroStats)",
    category: "home",
    component_type: "hero_stats",
    default_props: {
      title: "TIÊU ĐỀ TRANG",
      subtitle: "Mô tả ngắn, gọn và sắc nét cho trang.",
      stats: [{ value: "10+", label: "Dự án" }, { value: "5000+", label: "Học viên" }, { value: "50+", label: "Đối tác" }],
      backgroundFrom: "#050505",
      backgroundTo: "#ed1c24",
    },
    sort_order: 1,
    is_active: true,
  },
  {
    template_key: "about-gzv",
    name: "Giới Thiệu GZV (AboutGzv)",
    category: "home",
    component_type: "about_gzv",
    default_props: {
      title: "GZV LTD - HÀNH TRÌNH KIẾN TẠO",
      subtitle: "GZV Center được thành lập với sứ mệnh hỗ trợ và phát triển năng lực lãnh đạo cho thế hệ trẻ.",
      description: "Chúng tôi mang đến các chương trình huấn luyện, tư vấn chiến lược và môi trường trải nghiệm thực chiến.",
      image_url: "/placeholder.jpg",
      button_label: "XEM CÂU CHUYỆN GZV",
      button_url: "/gioi-thieu",
    },
    sort_order: 2,
    is_active: true,
  },
  {
    template_key: "projects-grid",
    name: "Dự Án Tiêu Biểu (ProjectsGrid)",
    category: "home",
    component_type: "projects_grid",
    default_props: {
      title: "DỰ ÁN TIÊU BIỂU",
      subtitle: "Những chiến dịch và dự án tiêu biểu do GZV cùng đối tác triển khai.",
      item_limit: 6,
      button_label: "XEM TẤT CẢ DỰ ÁN",
      button_url: "/du-an",
    },
    sort_order: 3,
    is_active: true,
  },
  {
    template_key: "services-three",
    name: "Dịch Vụ Cung Cấp (ServicesThree)",
    category: "home",
    component_type: "services_three",
    default_props: {
      title: "GIẢI PHÁP ĐÀO TẠO & PHÁT TRIỂN",
      subtitle: "Các gói giải pháp được thiết kế tối ưu cho cá nhân và tổ chức.",
    },
    sort_order: 4,
    is_active: true,
  },
  {
    template_key: "about-boxes",
    name: "Khối Sứ Mệnh & Tầm Nhìn (AboutBoxes)",
    category: "home",
    component_type: "about_boxes",
    default_props: {
      title: "GIÁ TRỊ CỐT LÕI CỦA GZV",
      items: [
        { title: "SỨ MỆNH", description: "Truyền cảm hứng và khai phóng tiềm năng của thế hệ trẻ Việt Nam.", icon: "target" },
        { title: "TẦM NHÌN", description: "Trở thành hệ sinh thái đào tạo & phát triển tư duy hàng đầu.", icon: "eye" },
        { title: "GIÁ TRỊ", description: "Chân thật - Đột phá - Bền vững - Đồng hành.", icon: "award" },
      ],
    },
    sort_order: 5,
    is_active: true,
  },
  {
    template_key: "partners-grid",
    name: "Đối Tác Đồng Hành (PartnersGrid)",
    category: "home",
    component_type: "partners_grid",
    default_props: {
      title: "ĐỐI TÁC ĐỒNG HÀNH KHẮP CẢ NƯỚC",
      subtitle: "GZV tự hào đồng hành cùng các tập đoàn và thương hiệu hàng đầu.",
    },
    sort_order: 6,
    is_active: true,
  },
  {
    template_key: "news-grid",
    name: "Tin Tức & Bài Viết Mới Nhất (NewsGrid)",
    category: "home",
    component_type: "news_grid",
    default_props: {
      title: "TIN TỨC & BÀI VIẾT MỚI NHẤT",
      subtitle: "Cập nhật những thông tin, sự kiện và bài viết chia sẻ tri thức mới nhất từ GZV.",
      item_limit: 3,
      button_label: "XEM TẤT CẢ BÀI VIẾT",
      button_url: "/tin-tuc",
    },
    sort_order: 7,
    is_active: true,
  },
  {
    template_key: "stats-bar",
    name: "Khối Con Số Thống Kê (StatsBar)",
    category: "content",
    component_type: "stats_bar",
    default_props: {
      badge: "KẾT QUẢ ẤN TƯỢNG",
      title: "NHỮNG CON SỐ BIẾT NÓI",
      subtitle: "Thành tựu và kết quả đo lường được trong suốt quá trình đồng hành và phát triển.",
      columns: 4,
      backgroundFrom: "#050505",
      backgroundTo: "#111111",
      accentColor: "#ed1c24",
      stats: [
        { value: "10+", label: "Năm kinh nghiệm", description: "Đồng hành và phát triển" },
        { value: "5000+", label: "Học viên", description: "Tham gia đào tạo" },
        { value: "50+", label: "Doanh nghiệp", description: "Đối tác chiến lược" },
        { value: "98%", label: "Hài lòng", description: "Đánh giá chất lượng" },
      ],
    },
    sort_order: 8,
    is_active: true,
  },
  {
    template_key: "feature-grid-red",
    name: "Lưới Giá Trị / Tính Năng (FeatureGrid)",
    category: "content",
    component_type: "feature_grid",
    default_props: {
      title: "GIÁ TRỊ NỔI BẬT",
      subtitle: "Các điểm mạnh có thể thêm, xóa, sửa trực tiếp trong props.",
      columns: 3,
      items: [
        { title: "Tư duy chiến lược", description: "Mô tả ngắn cho giá trị này.", icon: "target", color: "#ed1c24" },
        { title: "Triển khai thực chiến", description: "Mô tả ngắn cho giá trị này.", icon: "book", color: "#050505" },
        { title: "Đo lường kết quả", description: "Mô tả ngắn cho giá trị này.", icon: "award", color: "#ed1c24" },
      ],
    },
    sort_order: 10,
    is_active: true,
  },
  {
    template_key: "gallery-editor",
    name: "Bộ Ảnh Thư Viện (ImageGallery)",
    category: "media",
    component_type: "image_gallery",
    default_props: {
      title: "THƯ VIỆN HÌNH ẢNH",
      subtitle: "Quản lý từng ảnh, tiêu đề, mô tả và phân loại.",
      images: [
        { src: "/placeholder.jpg", title: "Ảnh 1", category: "GZV", description: "Mô tả ảnh", alt: "GZV" },
        { src: "/placeholder.jpg", title: "Ảnh 2", category: "GZV", description: "Mô tả ảnh", alt: "GZV" },
      ],
    },
    sort_order: 11,
    is_active: true,
  },
  {
    template_key: "rich-content",
    name: "Khối Nội Dung Rich Text (HtmlBlock)",
    category: "content",
    component_type: "html_rich",
    default_props: { maxWidth: "980px" },
    sort_order: 12,
    is_active: true,
  },
  {
    template_key: "contact-layout",
    name: "Form + Thông Tin Liên Hệ",
    category: "contact",
    component_type: "contact_section",
    default_props: {
      title: "KẾT NỐI VỚI CHÚNG TÔI",
      subtitle: "Để lại thông tin để nhận tư vấn nhanh nhất.",
      phone: "(+84) 329 381 489",
      email: "gzv.one@gmail.com",
      address: "279 Nguyễn Tri Phương, Phường Diên Hồng, TP.Hồ Chí Minh",
    },
    sort_order: 13,
    is_active: true,
  },
]

export const defaultNav: NavItem[] = [
  { href: "/", label_vi: "TRANG CHỦ", label_en: "HOME", sort_order: 5, is_visible: true, is_page_enabled: true },
  { href: "/gioi-thieu", label_vi: "GIỚI THIỆU", label_en: "ABOUT", sort_order: 10, is_visible: true, is_page_enabled: true },
  {
    href: "/dich-vu",
    label_vi: "DỊCH VỤ",
    label_en: "SERVICES",
    sort_order: 20,
    is_visible: true,
    is_page_enabled: true,
    children: [
      { href: "/dich-vu/marketing", label_vi: "MARKETING", label_en: "MARKETING", parent_href: "/dich-vu", sort_order: 10, is_visible: true, is_page_enabled: true },
      { href: "/cua-hang", label_vi: "CỬA HÀNG", label_en: "STORE", parent_href: "/dich-vu", sort_order: 20, is_visible: true, is_page_enabled: true },
    ],
  },
  { href: "/du-an", label_vi: "DỰ ÁN", label_en: "PROJECTS", sort_order: 30, is_visible: true, is_page_enabled: true },
  { href: "/gzver", label_vi: "GZVers", label_en: "GZVers", sort_order: 40, is_visible: true, is_page_enabled: true },
  { href: "/tin-tuc", label_vi: "TIN TỨC", label_en: "NEWS", sort_order: 50, is_visible: true, is_page_enabled: true },
  { href: "/lien-he", label_vi: "LIÊN HỆ", label_en: "CONTACT", sort_order: 60, is_visible: true, is_page_enabled: true },
]

export const quickBuilderPages = [
  { slug: "dich-vu", label: "Dịch vụ", hint: "Trang riêng /dich-vu" },
  { slug: "gioi-thieu", label: "Giới thiệu", hint: "Câu chuyện, sứ mệnh, tầm nhìn" },
  { slug: "du-an", label: "Dự án", hint: "Banner, block dự án" },
  { slug: "gzver", label: "GZVers", hint: "Cộng đồng, ban, profile" },
  { slug: "tin-tuc", label: "Tin tức", hint: "Banner và block nội dung tin" },
  { slug: "lien-he", label: "Liên hệ", hint: "Form, map, thông tin liên hệ" },
]

export const defaultLoading: LoadingSettings = { id: 1, logo_url: "/logo.webp", title: "GZV", subtitle: "Đang tải dữ liệu...", effect: "orbit", background_from: "#050505", background_to: "#ed1c24", accent_color: "#ed1c24", enabled: true, minimum_duration_ms: 900 }
export const defaultBranding: BrandingSettings = { id: 1, site_name: "GZV", header_logo_url: "/logo.webp", footer_logo_url: "/logo.webp", favicon_url: "/logo/favicon.ico", default_title: "GZV - The Voice of Genzers", title_template: "%s | GZV", default_description: "GZV Center", default_keywords: "GZV, đào tạo, mentoring, coaching", og_image_url: "/og-image.jpg", topbar_email_label: "gzv.one@gmail.com", topbar_phone_label: "(+84) 329 381 489", topbar_badge_label: "GZV" }
export const defaultFooter: FooterSettings = {
  id: 1,
  logo_url: "/logo.webp",
  intro_text: "GZV - The Voice of Genzers",
  background_color: "#050505",
  bottom_background_color: "#111111",
  facebook_page_url: "https://www.facebook.com/gzv.one",
  address: "279 Nguyễn Tri Phương, Phường Diên Hồng, TP.Hồ Chí Minh",
  phone_label: "Điện Thoại: (+84) 329 381 489",
  phone_url: "tel:+84329381489",
  email_label: "Email: gzv.one@gmail.com",
  email_url: "mailto:gzv.one@gmail.com",
  newsletter_title: "Kết nối với chúng tôi",
  newsletter_description: "Đăng ký để nhận thông tin về các khóa học và sự kiện mới nhất.",
  copyright_text: "gzv Center. Phát triển bởi Phòng Công nghệ thông tin.",
  links: [],
  social_links: [],
}

export const defaultBannerConfig = {
  badge: "GZV CENTER",
  title: "TIÊU ĐỀ BÌA CỦA TRANG",
  subtitle: "Mô tả ngắn gọn sắc nét cho banner trang",
  use_image: true,
  cover_url: "/placeholder.jpg",
  imagePositionY: "50%",
  image_opacity: 100,
  image_grayscale: false,
  overlay_enabled: true,
  overlay_color: "#050505",
  overlay_opacity: 60,
  bg_color: "#050505",
  bg_from: "#050505",
  bg_to: "#ed1c24",
  titleAlignment: "center" as "left" | "center" | "right",
  show_badge: true,
  show_title: true,
  show_subtitle: true,
  badge_color: "#ffffff",
  title_color: "#ffffff",
  subtitle_color: "rgba(255,255,255,0.85)",
}

export const defaultPageBlocks: PageBlock[] = [
  // 1. Dịch vụ (/dich-vu)
  {
    page_slug: "dich-vu",
    block_key: "stats",
    component_type: "stats_bar",
    title: "CON SỐ THỐNG KÊ DỊCH VỤ",
    props: {
      badge: "KẾT QUẢ ĐO LƯỜNG",
      title: "NĂNG LỰC THỰC CHIẾN GZV",
      subtitle: "Marketing | Sales | Digital Transformation",
      stats: [
        { value: "3", label: "Mũi triển khai", description: "Marketing, Sales, Chuyển đổi số" },
        { value: "50+", label: "Đối tác", description: "Doanh nghiệp đồng hành" },
        { value: "10+", label: "Lĩnh vực", description: "Kinh nghiệm thực tiễn" },
        { value: "100%", label: "Thực chiến", description: "Tập trung vào kết quả" },
      ],
      backgroundFrom: "#050505",
      backgroundTo: "#111111",
      accentColor: "#ed1c24",
    },
    sort_order: 10,
    is_visible: true,
  },
  {
    page_slug: "dich-vu",
    block_key: "services",
    component_type: "services_three",
    title: "SERVICES",
    props: {
      title: "SERVICES",
      subtitle: "Marketing | Sales | Digital Transformation",
      items: [
        { title: "Marketing", icon: "megaphone", description: "Xây dựng chiến lược thương hiệu, nội dung, chiến dịch tăng trưởng và truyền thông đa kênh." },
        { title: "Sales", icon: "trend", description: "Thiết kế pipeline, kịch bản bán hàng, đào tạo đội ngũ và tối ưu chuyển đổi doanh thu." },
        { title: "Digital Transformation", icon: "cpu", description: "Chuẩn hóa quy trình, dữ liệu, tự động hóa và công cụ vận hành cho doanh nghiệp." },
      ],
    },
    sort_order: 20,
    is_visible: true,
  },
  {
    page_slug: "dich-vu",
    block_key: "mentoring_model",
    component_type: "mentoring_model",
    title: "QUY TRÌNH TRIỂN KHAI",
    props: {
      title: "QUY TRÌNH TRIỂN KHAI",
      subtitle: "Lộ trình đồng hành thực chiến cùng doanh nghiệp",
    },
    sort_order: 30,
    is_visible: true,
  },
  {
    page_slug: "dich-vu",
    block_key: "why_columns",
    component_type: "why_columns",
    title: "TẠI SAO CHỌN GZV",
    props: {
      title: "TẠI SAO CHỌN GZV",
      subtitle: "Khác biệt tạo nên hiệu quả",
    },
    sort_order: 40,
    is_visible: true,
  },
  {
    page_slug: "dich-vu",
    block_key: "cta",
    component_type: "cta_band",
    title: "SẴN SÀNG TRAO ĐỔI BÀI TOÁN TĂNG TRƯỜNG",
    props: {
      title: "SẴN SÀNG TRAO ĐỔI BÀI TOÁN TĂNG TRƯỜNG",
      subtitle: "Gửi thông tin để đội ngũ GZV tư vấn hướng triển khai phù hợp nhất.",
      button_label: "Đăng ký tư vấn ngay",
      button_url: "/lien-he",
      background_from: "#050505",
      background_to: "#ed1c24",
    },
    sort_order: 50,
    is_visible: true,
  },

  // 2. Dự án (/du-an)
  {
    page_slug: "du-an",
    block_key: "stats",
    component_type: "stats_bar",
    title: "THỐNG KÊ DỰ ÁN",
    props: {
      badge: "DẤU ẤN TRIỂN KHAI",
      title: "TỔNG QUAN DỰ ÁN",
      subtitle: "Các dự án Mentoring & Coaching thực tế mà GZV Center đã triển khai.",
      stats: [
        { value: "10+", label: "Dự án tiêu biểu" },
        { value: "50+", label: "Doanh nghiệp" },
        { value: "5000+", label: "Học viên" },
        { value: "10+", label: "Lĩnh vực" },
      ],
      backgroundFrom: "#050505",
      backgroundTo: "#111111",
      accentColor: "#ed1c24",
    },
    sort_order: 10,
    is_visible: true,
  },
  {
    page_slug: "du-an",
    block_key: "projects",
    component_type: "projects_grid",
    title: "DANH SÁCH DỰ ÁN",
    props: {
      title: "DỰ ÁN ĐÃ TRIỂN KHAI",
      subtitle: "Những chiến dịch và dự án tiêu biểu do GZV cùng đối tác triển khai",
      show_search: true,
      show_categories: true,
      limit: 12,
    },
    sort_order: 20,
    is_visible: true,
  },
  {
    page_slug: "du-an",
    block_key: "cta",
    component_type: "cta_band",
    title: "KÊU GỌI HÀNH ĐỘNG (CTA)",
    props: {
      title: "Bạn có dự án cần triển khai?",
      subtitle: "Hãy để GZV Center trở thành đối tác đồng hành, thiết kế chương trình đào tạo riêng biệt và hiệu quả cho tổ chức của bạn.",
      button_label: "Liên hệ ngay",
      button_url: "/lien-he",
      background_from: "#050505",
      background_to: "#ed1c24",
    },
    sort_order: 30,
    is_visible: true,
  },

  // 3. GZVers (/gzver)
  {
    page_slug: "gzver",
    block_key: "stats",
    component_type: "stats_bar",
    title: "QUY MÔ NHÂN SỰ",
    props: {
      badge: "HỆ SINH THÁI GZV",
      title: "QUY MÔ ĐỘI NGŨ",
      subtitle: "Hệ sinh thái con người tạo nên giá trị và sự khác biệt tại GZV Center.",
      stats: [
        { value: "50+", label: "GZVers" },
        { value: "10+", label: "Cố vấn & Mentor" },
        { value: "5+", label: "Ban chuyên môn" },
        { value: "100%", label: "Thực chiến" },
      ],
      backgroundFrom: "#050505",
      backgroundTo: "#111111",
      accentColor: "#ed1c24",
    },
    sort_order: 10,
    is_visible: true,
  },
  {
    page_slug: "gzver",
    block_key: "gzvers_list",
    component_type: "gzvers_grid",
    title: "DANH SÁCH GZVERS",
    props: {
      title: "DANH SÁCH GZVERS",
      subtitle: "Đội ngũ nhân sự, cố vấn và chuyên gia đồng hành",
      show_filter: true,
      limit: 20,
    },
    sort_order: 20,
    is_visible: true,
  },
  {
    page_slug: "gzver",
    block_key: "cta",
    component_type: "cta_band",
    title: "GIA NHẬP GZV",
    props: {
      title: "Gia nhập đại gia đình GZV",
      subtitle: "Trở thành một phần của cộng đồng trẻ năng động, sáng tạo và bứt phá giới hạn.",
      button_label: "Ứng tuyển ngay",
      button_url: "/lien-he",
      background_from: "#050505",
      background_to: "#ed1c24",
    },
    sort_order: 30,
    is_visible: true,
  },

  // 4. Tin tức (/tin-tuc)
  {
    page_slug: "tin-tuc",
    block_key: "news_list",
    component_type: "news_grid",
    title: "DANH SÁCH TIN TỨC",
    props: {
      title: "TIN TỨC MỚI NHẤT",
      subtitle: "Tổng hợp các bài viết nổi bật, xu hướng ngành và hoạt động của GZV",
      limit: 9,
      show_categories: true,
    },
    sort_order: 10,
    is_visible: true,
  },
  {
    page_slug: "tin-tuc",
    block_key: "cta",
    component_type: "cta_band",
    title: "BẢN TIN GZV",
    props: {
      title: "Đăng ký nhận bản tin GZV",
      subtitle: "Nhận các bài viết chuyên sâu và xu hướng thị trường hàng tuần từ đội ngũ chuyên gia.",
      button_label: "Đăng ký ngay",
      button_url: "/lien-he",
      background_from: "#050505",
      background_to: "#ed1c24",
    },
    sort_order: 20,
    is_visible: true,
  },

  // 5. Liên hệ (/lien-he)
  {
    page_slug: "lien-he",
    block_key: "contact_block",
    component_type: "contact_form",
    title: "FORM LIÊN HỆ & THÔNG TIN",
    props: {
      title: "GỬI THÔNG TIN CHO GZV",
      subtitle: "Chúng tôi sẽ phản hồi trong vòng 24 giờ làm việc.",
      email: "one.gzv@gmail.com",
      phone: "(+84) 329 381 489",
    },
    sort_order: 10,
    is_visible: true,
  },
  {
    page_slug: "lien-he",
    block_key: "cta",
    component_type: "cta_band",
    title: "HOTLINE HỖ TRỢ",
    props: {
      title: "Sẵn sàng bứt phá cùng GZV?",
      subtitle: "Đội ngũ chuyên gia luôn sẵn sàng đồng hành cùng bạn trên hành trình phát triển.",
      button_label: "Gọi Hotline ngay",
      button_url: "tel:0329381489",
      background_from: "#050505",
      background_to: "#ed1c24",
    },
    sort_order: 20,
    is_visible: true,
  },
]

export function normalizeSlug(str: string) {
  return str
    .toLowerCase()
    .trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\u0111/g, "d")
    .replace(/\u0110/g, "d")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
}
