import { CV_TEMPLATES, normalizeTemplate, type CvTemplate } from "./cv-model"

export function CvTemplatePicker({ value, onChange }: { value: string; onChange: (template: CvTemplate, accent: string) => void }) {
  return <div className="cv-template-picker" role="group" aria-label="Chọn thiết kế CV">
    {CV_TEMPLATES.map((template) => <button key={template.id} type="button" aria-pressed={normalizeTemplate(value) === template.id} className={`cv-template-option ${normalizeTemplate(value) === template.id ? "cv-template-selected" : ""}`} onClick={() => onChange(template.id, template.color)}>
      <span className={`cv-template-mini cv-template-mini-${template.id}`} style={{ background: template.background, color: template.id === "midnight" ? "#fff" : "#172033", "--mini-accent": template.color } as any} aria-hidden="true"><span className="cv-mini-brand">GZV</span><span className="cv-mini-title">Aa<span>PORTFOLIO / CV</span></span><span className="cv-mini-photo" /><span className="cv-mini-sidebar"><i /><i /><i /></span><span className="cv-mini-main"><i /><i /><i /></span><span className="cv-mini-project" /></span>
      <span className="cv-template-name">{template.name}<span>{normalizeTemplate(value) === template.id ? "✓" : ""}</span></span><span className="cv-template-caption">{template.caption}</span>
    </button>)}
    <style>{`.cv-template-picker{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.cv-template-option{text-align:left;border:1px solid #dce1e8;padding:10px;background:#fff;color:#172033;cursor:pointer;border-radius:5px;transition:border-color .15s,transform .15s}.cv-template-option:hover{transform:translateY(-2px);border-color:#ed1c24}.cv-template-selected{border:2px solid #ed1c24;padding:9px}.cv-template-mini{display:block;position:relative;height:130px;border-radius:3px;overflow:hidden;padding:12px}.cv-mini-brand{position:absolute;top:10px;left:12px;font-size:8px;font-weight:900;color:var(--mini-accent)}.cv-mini-title{position:absolute;top:27px;left:12px;font-size:27px;line-height:1;font-weight:800}.cv-mini-title>span{display:block;margin-top:4px;font-size:4px;letter-spacing:1px}.cv-mini-photo{position:absolute;top:27px;right:12px;width:27px;height:35px;background:var(--mini-accent);opacity:.55;border-radius:2px}.cv-mini-sidebar{position:absolute;top:74px;left:12px;width:28%;height:44px;background:var(--mini-accent);opacity:.2;padding:5px}.cv-mini-main{position:absolute;top:74px;left:46%;right:12px;padding-top:1px}.cv-mini-sidebar i,.cv-mini-main i{display:block;height:2px;margin-bottom:6px;background:currentColor;opacity:.4}.cv-mini-project{display:none}.cv-template-mini-minimal .cv-mini-sidebar{display:none}.cv-template-mini-minimal .cv-mini-main{left:12px}.cv-template-mini-minimal .cv-mini-photo{border-radius:50%;height:27px}.cv-template-mini-midnight .cv-mini-sidebar{left:auto;right:12px}.cv-template-mini-midnight .cv-mini-main{left:12px;right:46%}.cv-template-mini-editorial .cv-mini-title{font-family:Georgia,serif;font-weight:400}.cv-template-mini-editorial .cv-mini-sidebar{background:none;border-right:1px solid currentColor}.cv-template-mini-studio .cv-mini-title{background:var(--mini-accent);color:#fff;left:8px;right:8px;padding:5px;font-size:23px}.cv-template-mini-studio .cv-mini-photo{top:31px;background:#fff;opacity:.6;border-radius:20px 20px 2px 2px}.cv-template-mini-portfolio .cv-mini-main{display:none}.cv-template-mini-portfolio .cv-mini-sidebar{width:100%;height:1px}.cv-template-mini-portfolio .cv-mini-project{display:block;position:absolute;left:12px;right:12px;bottom:10px;height:37px;background:var(--mini-accent);opacity:.25}.cv-template-name{display:flex;justify-content:space-between;margin-top:9px;font-size:12px;font-weight:800}.cv-template-name>span{color:#ed1c24}.cv-template-caption{display:block;font-size:9px;color:#637083;margin-top:3px;line-height:1.5}@media(max-width:480px){.cv-template-picker{grid-template-columns:repeat(2,minmax(0,1fr))}.cv-template-mini{height:116px}.cv-mini-sidebar,.cv-mini-main{top:70px}}`}</style>
  </div>
}
