-- Add a managed gallery section to the end of the About page.
insert into public.site_page_blocks
  (page_slug, block_key, component_type, title, props, content_html, sort_order, is_visible)
values
  ('gioi-thieu', 'gallery', 'image_gallery', 'Thư viện ảnh',
   '{"title":"THƯ VIỆN ẢNH","subtitle":"Những khoảnh khắc, dự án và dấu ấn của GZV.","images":[]}'::jsonb,
   null, 100, true)
on conflict (page_slug, block_key) do update set
  component_type = excluded.component_type,
  title = excluded.title,
  sort_order = excluded.sort_order;

create table if not exists public.social_automation_settings (
  id bigint generated by default as identity primary key,
  is_enabled boolean not null default false,
  timezone text not null default 'Asia/Ho_Chi_Minh',
  ai_provider text not null default 'openai',
  default_prompt text,
  default_hashtags text,
  approval_required boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.social_automation_connections (
  id uuid primary key default gen_random_uuid(),
  platform text not null check (platform in ('facebook','instagram','tiktok','youtube','linkedin')),
  account_label text,
  status text not null default 'disconnected' check (status in ('disconnected','pending','connected','error')),
  external_account_id text,
  scopes text[] not null default '{}',
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(platform, external_account_id)
);

create table if not exists public.social_automation_jobs (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  source_type text not null check (source_type in ('article','project','custom')),
  source_id uuid,
  payload jsonb not null default '{}'::jsonb,
  platforms text[] not null default '{}',
  scheduled_at timestamptz,
  status text not null default 'draft' check (status in ('draft','scheduled','publishing','published','failed','cancelled')),
  results jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.social_automation_settings enable row level security;
alter table public.social_automation_connections enable row level security;
alter table public.social_automation_jobs enable row level security;

grant select, insert, update, delete on public.social_automation_settings to authenticated;
grant select, insert, update, delete on public.social_automation_connections to authenticated;
grant select, insert, update, delete on public.social_automation_jobs to authenticated;

create policy "automation admins manage settings" on public.social_automation_settings
  for all to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
create policy "automation admins manage connections" on public.social_automation_connections
  for all to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
create policy "automation admins manage jobs" on public.social_automation_jobs
  for all to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));
